version: '2.23'
services:
  gatewayserver:
    image: docker.io/library/api-gateway:v1.0.0
    ports:
      - "8080:8080"
  userserver:
    image: docker.io/library/user-service:v1.0.0
    ports:
      - "8082:8082"
    depends_on:
      - user_db
  user_db:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "user_db"
  homeserver:
    image: docker.io/library/home-service:v1.0.0
    ports:
      - "8081:8081"
    depends_on:
      - home_db
  home_db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "home_db"
  deviceserver:
    image: docker.io/library/device-service:v1.0.0
    environment:
      JAVA_OPTS: >-
        --add-opens=java.base/java.lang=ALL-UNNAMED
        --add-opens=java.management/sun.management=ALL-UNNAMED
        --add-opens=java.base/sun.net=ALL-UNNAMED
    ports:
      - "8083:8083"
    depends_on:
      - device_db
  device_db:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "device_db"
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
    - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafkaserver:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafkaserver:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CREATE_TOPICS=users:1:1,homes:1:1,rooms:1:1
    depends_on:
      - zookeeper
  zoonavigator:
    image: elkozmon/zoonavigator:latest
    ports:
      - "9000:9000"